default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: askme_development

test:
  <<: *default
  database: askme_test

production:
  <<: *default
  database: <%= ENV['ASKME_DATABASE_NAME'] %>
  username: <%= ENV['ASKME_DATABASE_USERNAME'] %>
  host: localhost
  password: <%= ENV['ASKME_DATABASE_PASSWORD'] %>